### PR TITLE
Fix getting product versions containing plus

### PR DESCRIPTION
**Pull request by hluk**

### CODE REVIEW

**Comment by xiangge** [comment]
Nice patch, lgtm

**Comment by ktdreyer** [comment]
Thanks! I seem to recall we have a couple more occurrences of this same pattern lurking elsewhere :(

**Comment by ktdreyer** [comment]
GitHub Actions published this as version `0.0.300` in [Ansible Galaxy](https://galaxy.ansible.com/ktdreyer/errata_tool_ansible).

**Comment by xiangge** [comment]
Thank @ktdreyer @hluk , the PV is special one as it is parsed as the parameter. Like the release is doing well I believe.

**Comment by ktdreyer** [comment]
Ok, I remember now fixing `release` in https://github.com/ktdreyer/errata-tool-ansible/pull/203, thanks.

**Pull request merged**
