### PR TITLE
Feat(CWFCONF-8260): Add allow_unreleased_rpms for product_versions

### PR DESCRIPTION
**Pull request by CryptoRodeo**
Fixes: #259

JIRA: CWFCONF-8260

### CODE REVIEW

**Comment by CryptoRodeo** [comment]
Hi @ktdreyer , here is the patch for allowing users with the `product-configuration-manager` role to set this value: https://code.engineering.redhat.com/gerrit/c/errata-rails/+/448317/3/app/models/concerns/user_permissions.rb#71

I'm wondering if the user in the ET test container will need it's roles updated too?

**Comment by CryptoRodeo** [comment]
Hey @ktdreyer , I have a question about the `create_product_version` function here: https://github.com/ktdreyer/errata-tool-ansible/blob/master/library/errata_tool_product_version.py#L199

After testing this locally, I noticed that the `allow_unreleased_rpms` value only got updated if the product version exists. Is this intended? I noticed that `params` gets passed, but only the specified values in the `pv` dict seem to get sent.

**Comment by ktdreyer** [comment]
That's a _great_ point. I have no explanation for why `create_product_version()` is handling those parameters individually. (Maybe this was from a super-early version of the code when I was experimenting with the entire concept of doing this stuff in Python and Ansible at all?)

Looking at it today, I think  `create_product_version()` should simply cast those specific boolean values to bools or ints, and then pop `product`, and then pass in any other `param` as-is. Ideally it should be as simple as `create_variant()`.

**Comment by ktdreyer** [comment]
I've updated the integration test VMs to errata-rails `4.34-0-6-g45d05d711` today.

**Comment by CryptoRodeo** [comment]
I'll create an MR to update `create_product_version()` soon if it makes sense?
> I've updated the integration test VMs to errata-rails 4.34-0-6-g45d05d711 today.

Nice! Want me to re-push so we can test this with the new VMs?

**Comment by ktdreyer** [comment]
Sure, that would be good. Then we can merge this.

**Comment by ktdreyer** [comment]
I reinitialized the rhel-7 and rhel-8 VMs, and they both fail to start the errata-rails containers at `Devel database init`. I'll follow-up with you next week about this.

**Comment by ktdreyer** [comment]
I've opened RHELWF-10345 with the docker-compose issues.

**Comment by ktdreyer** [comment]
- I've gotten `docker-compose` working on the el8 integration test server now. I applied the patches I've submitted in RHELWF-10345.
- I'm going to remove el7 in https://github.com/ktdreyer/errata-tool-ansible/pull/319
- After removing el7 and ensuring I'm running the latest errata-rails version on el8, I hit this bug: https://github.com/ktdreyer/errata-tool-ansible/issues/320

**Comment by CryptoRodeo** [comment]
Thanks for following up @ktdreyer , I'll work on the fix for issue #320 next sprint.
There is also a related issue I filed here: #305 . I can create a separate ticket for this too.

**Comment by ktdreyer** [comment]
Thanks for offering to work on #320. I want to land this feature `allow_unreleased_rpms` for my product (Ceph 7.1 coming up), so I've fixed #320 today. I'm going to rebase this branch on that now.

**Pull request merged**
