### PR TITLE
Support multiple product variants for CDN repos

### PR DESCRIPTION
**Pull request by hongweiliu17**

### CODE REVIEW

**Comment by ktdreyer** [comment]
Thank you very much for this PR.

It is possible to set multiple variants for CDN repos. You can do it like this:

```yaml
- name: Add redhat-rhceph-rhceph-4-rhel8 cdn repo
  errata_tool_cdn_repo:
    name: redhat-rhceph-rhceph-4-rhel8
    release_type: Primary
    content_type: Docker
    variants:
    - 8Base-RHCEPH-4.0-Tools
    - 8Base-RHCEPH-4.1-Tools
    packages:
      rhceph-container:
      - latest
      - "{{ '{{' }}version{{ '}}' }}"
      - "{{ '{{' }}version{{ '}}' }}-{{ '{{' }}release{{ '}}' }}"
```

Ansible will add or remove any variants according to the list. I've updated the docs to make this explicit, https://github.com/ktdreyer/errata-tool-ansible/pull/146

One nice thing about the current behavior is that I can *remove* variants. For example, here's a Git diff that would lead Ansible to delete a variant relationship for this repo:

```diff
--- a/roles/rhceph/tasks/cdn-repo.yml
+++ b/roles/rhceph/tasks/cdn-repo.yml
@@ -5,7 +5,6 @@
     content_type: Docker
     variants:
       - 8Base-RHCEPH-4.0-Tools
-      - 8Base-RHCEPH-4.1-Tools
     packages:
       rhceph-container:
         - latest
```

Here are some examples of why I would want to do this:
- If I incorrectly set the wrong variant on a CDN repo, I can un-do that change with code, eg `git revert` to go back to a known-good state.
- If I'm experimenting in the ET dev or stage environment (let's say I'm creating the *next* version, eg RHCS 4.2 or 4.3), I can quickly and safely un-do my changes by applying my playbook's `master` branch.
- If some other engineer made some changes to the ET CDN repo configuration outside of Ansible without telling anyone, then the next time I run Ansible, the output will show me that someone changed something. I can go back and work together with my teammate to capture that change in Ansible instead so the configuration is audit-able and repeatable.
- If I don't need the variant any more (for a business reason), removing it is a one-line change that is easy to review with `git diff`.

If that particular `variants` list is coming from elsewhere, it's possible to assemble that list and then pass it into the `errata_tool_cdn_repo` task. I can help with that if you want as well.

**Comment by hongweiliu17** [comment]
Thanks very much for your detailed comment. I understand your design now.
The current design is very convenient if we want to undo or revert some change. But it doesn't work if we want to just unlink a repo from a variant by removing one variant from the script but which was not linked right by the ansible.
I guess in the future, more existing products will use the script, how to manage their existing repo and variants?
In ET, there is no restapi to unlink a repo from a variant. Maybe we can file an ET RFE if we need unlink api except for webui unlink way?
And how about we provide a 'add' and 'remove' function in ansible to remove and add variants basing on the old variant list? So the ansible can handle them if anyone wants to add variant or remove variant any time, this is just my personal thought, you may ignore it if it is not a good idea :).
Thanks for the ansible script.

**Comment by ktdreyer** [comment]
After our discussion with @ian-panzica in chat, I'm going to make  `variants` an optional parameter https://github.com/ktdreyer/errata-tool-ansible/issues/157 . This will make it easier for the HoneyBadger team to use the `errata_tool_cdn_repo` module without wiping the by-hand configurations that are currently in place.

It is still not yet possible to *set* individual `errata_tool_cdn_repo` variants in Ansible without removing the others. For that, I'm considering adding a new `errata_tool_cdn_repo_variants` module like what we did for [`koji_tag_inheritance`](https://github.com/ktdreyer/koji-ansible#koji_tag_inheritance) or [`koji_tag_packages`](https://github.com/ktdreyer/koji-ansible#koji_tag_packages).

Long-term, let's make it easy to track the full list of variants in HoneyBadger instead of using `errata_tool_cdn_repo_variants`. When we set individual relationships like that without declaring the full configurations, it leaves HoneyBadger's system vulnerable to configuration drift, and if we're maintaining HoneyBadger for multiple years, that gets challenging.

**Comment by hongweiliu17** [comment]
Thanks a lot! Let me close this PR.

**Comment by hongweiliu17** [comment]
Close it.

**Pull request closed without merging**
