### PR TITLE
Avoid raising exception during check_mode query

### PR DESCRIPTION
**Pull request by ian-panzica**
A non-existent errata product should not cause the product version task
to fail when running in check mode. It could be that the product will be
created along with the product version. The task should not fail in this
case because it would be expected.

### CODE REVIEW

**Comment by ian-panzica** [comment]
Is this fork related?

```
++ git rev-list --max-parents=0 HEAD
+ BASE_COMMIT=8e12e0f0ffa5b3097106a5bd471a99381cb6ecc9
++ git rev-list --count 8e12e0f0ffa5b3097106a5bd471a99381cb6ecc9..HEAD
+ COMMIT_COUNT=-1
+ VERSION=0.0.-1
+ sed /home/runner/work/errata-tool-ansible/errata-tool-ansible/galaxy.yml -e 's/{{ version }}/0.0.-1/'
```

**Comment by ktdreyer** [comment]
Yeah looks like that `COMMIT_COUNT` calculation has been broken for a long time. I filed https://github.com/ktdreyer/errata-tool-ansible/issues/193 to track that.

**Comment by ktdreyer** [comment]
This looks good.

I think I've fixed the CI today, so I'm going to do more testing tomorrow.

**Comment by ktdreyer** [comment]
still doing more testing

**Comment by ian-panzica** [comment]
@ktdreyer I saw there was some new code in master so I went ahead and rebased on that. Hopefully that doesn't cause any issues!

**Comment by ktdreyer** [comment]
That is fine, thanks for rebasing!

This problem triggered something in my memory because it seems familiar. I went looking, and it's similar to what we implemented a while ago for koji tag inheritance with missing parents, in https://github.com/ktdreyer/koji-ansible/pull/39

I wrote some integration tests for `errata_tool_product_version` and I'll create the PR for those after I merge this.

**Review by ktdreyer — APPROVED** [review]

**Comment by ktdreyer** [comment]
https://github.com/ktdreyer/errata-tool-ansible/pull/199 adds the integration tests for this.

**Pull request merged**
